server {
    listen 80;
    server_name amc.caja amc.cuentaspagar amc.cuentasporpagar amc.pedidos amc.dashboard synapse.amc amc.synapse localhost;

    # Servir Frontend
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ =404;
    }

    # Proxy a Backend Synapse API global
    location /api/ {
        proxy_pass http://synapse-api:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy para el módulo de Caja
    location /caja/ {
        proxy_pass http://synapse-api:8000/caja/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
